# Generated by Django 5.2.1 on 2025-06-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_metric_name')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('comparison', models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equal'), ('<=', 'Less or equal'), ('==', 'Equal')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='MAH_App.metric')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metric', 'threshold', 'comparison'), name='unique_alert_per_metric_rule')],
            },
        ),
    ]
