# Generated by Django 5.2.1 on 2025-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAH_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_name',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
